# Generated by Django 3.0.8 on 2020-07-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_registration',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Phone_Number', models.IntegerField(unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
